<?php

print "<!DOCTYPE html>\n";
print "<html lang=\"en-GB\">\n";
print "            \n";
print "    <head>       \n";
print "        <meta charset=\"utf-8\">\n";
print "        <meta name=\"author\" content=\"learn.expandedmetrics.com\">\n";
print "        <meta name=\"description\" content=\" \">\n";
print "        <meta name=\"keywords\" content=\" \">\n";
print "        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
print "            \n";
print "        <title>D12.E1 · Multipage PHP website</title>\n";
print "\n";
print "        <!-- Socials -->\n";
print "        <meta property=\"og:title\" content=\" \" />\n";
print "        <meta property=\"og:type\" content=\"website\" />\n";
print "        <meta property=\"og:description\" content=\" \" />\n";
print "        <meta property=\"og:image\" content=\"assets/ .jpg\" />\n";
print "        <meta property=\"og:url\" content=\" .com\" />\n";
print "        <meta name=\"twitter:title\" content=\" \">\n";
print "        <meta name=\"twitter:description\" content=\" \">\n";
print "        <meta name=\"twitter:image\" content=\"assets/ .jpg\">\n";
print "        <meta name=\"twitter:card\" content=\"assets/ .jpg\">\n";
print "\n";
print "        <!-- CSS -->\n";
print "        <link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\n";
print "                \n";
print "        <!--JavaScript -->\n";
print "        <script type=\"text/javascript\" src=\"Exersice10.js\" defer></script> \n";
print "\n";
print "        <!-- Favicons -->\n";
print "        <link rel=\"shortcut icon\" href=\"assets/favicon.ico\"> \n";
print "\n";
print "    </head>       \n";
print "\n";
print "    <body>\n";
print "        \n";
print "        <header><a href=\"index.php\">MULTIPAGE PHP WEBSITE</a></header>\n";
print "\n";
print "        <div class=\"content-wrap\">\n";
print "        \n";
print "            <main>\n";
print "                <h1>Artem Kostyukevich</h1>\n";
print "                \n";
print "                <figure>\n";
print "                    <img src=\"images/img1.jpg\">\n";
print "                    <img src=\"images/img2.jpg\">                        \n";
print "                    <figcaption><em>From the book 'Shadows'</em></figcaption>\n";
print "                </figure>\n";
print "\n";
print "                <p>Artem Kostyukevich was born in 1971 in Omsk. Artem graduated Leningrad School of Arts named after V. Serov (now St. Petersburg School of Arts named after N.K.Roerich). He studied at St. Petersburg State Pedagogical University named after A.I.Herzen (department of fine arts) and graduated from HAW Hamburg Institute (department of design and illustration).</p>\n";
print "                <p>Artem (voller Name Artem Kostyukevich), geboren 1971 in Omsk (Russland), lebt seit 1999 in Deutschland. Er studiert Kinder- und Jugendbuchillustration an der Hochschule für Angewandte Wissenschaften Hamburg. Zuvor hat er in St. Petersburg an der Kunstlehranstalt \"W.A.Serow\" studiert und an der Pädagogischen Universität \"A.I.Herzen\" das Fach Darstellende Kunst belegt. Seine Illustrationen wurden unter anderem auf der Kinderbuchmesse in Bologna ausgestellt. Artem lebt mit seiner Familie in Hamburg.</p>\n";
print "\n";
print "            </main>\n";
print "        \n";
print "            <aside>\n";
print "\n";
print "                <nav>\n";
print "                    <p>POSTS:</p>\n";
print "                    <!-- section 1 menu-->\n";
print "                    <a class=\"sectiontitle\" id=\"\">Section 1</a>\n";
print "                    <ul>\n";
print "                        <li><a href=\"aretm.php\" id=\"\">Artem Kostyukevich</a></li>\n";
print "                        <li><a href=\"page1.php\">Page 1</a></li>\n";
print "                        <li><a href=\"page2.php\">Page 2</a></li>\n";
print "\n";
print "                    </ul>\n";
print "                    \n";
print "                    <!-- section 2 menu-->\n";
print "                    <a class=\"sectiontitle\">Section 2</a>\n";
print "                    <ul>\n";
print "                        <li><a href=\"page3.php\">Page 3</a></li>\n";
print "                        <li><a href=\"page4.php\">Page 4</a></li>\n";
print "                        <li><a href=\"page5.php\">Page 5</a></li>\n";
print "                    </ul>         \n";
print "\n";
print "                    <a href=\"about.php\">About</a>\n";
print "\n";
print "                </nav>\n";
print "                <br>\n";
print "                <hr>\n";
print "                <p class=\"s\">(This is an extra paragraph in the aside element)</p>\n";
print "            </aside>\n";
print "        </div>\n";
print "        \n";
print "        <footer><p class=\"s\">Footer text comes here</p></footer>\n";
print "\n";
print "    </body>\n";
print "</html>\n";
print "\n";
print "\n";
print "\n";
print "<!-- REFERENCE PHP CODE: -->\n";
print "<!--\n";
print "Declare variables\n";
print "<?php $thisSection=\"\"; ?>\n";
print "\n";
print "Echo function w. if statement\n";
print "<?php if ($thisPage!=\"\") echo \"$thisPage\"; ?>\n";
print "\n";
print "Include function\n";
print "<?php include(\"php/something.php\"); ?>\n";
print "\n";
print "Add an ID to an element dynamically\n";
print "<?php if ($thisPage==\"Page One\") echo \" id=\"currentpage\"\"; ?>\n";
print "Add this as an attribute within an element\n";
print "\n";
print "Date\n";
print "<?php\n";
print "date_default_timezone_set('Asia/Kolkata');\n";
print "echo \"\" . date(\"Y\") ;\n";
print "?>\n";
print "-->";

?>
